### PR TITLE
Replace which -s with command -v

### PR DESCRIPTION
**Pull request by blacked**
Command -v "cmd" is preferred way to test if command available. 
http://unix.stackexchange.com/questions/85249/why-not-use-which-what-to-use-then

### CODE REVIEW

**Comment by ikenigma** [comment]
Hi @blacked, thanks - but can you re-submit without all the whitespace changes please?

Otherwise, I'm carefully considering your commit.

Thank you!

**Comment by ikenigma** [comment]
@blacked after a bit more testing, and a second read-through of what you posted, I'm quite convinced in the long-term portability of 'command -v' over 'which'.

Please resubmit without the whitespace changes, and thank you!

**Comment by dotike** [comment]
@blacked I have taken the liberty to slice apart your commit into two commits, and resubmitted as another PR just now.

This PR can be closed, replaced by PR #3

**Comment by mikelenigma** [comment]
Closing since PR #3 addresses this.

**Pull request closed without merging**
